export const FETCH_TESTIMONIALS_REQUEST = "FETCH_TESTIMONIALS_REQUEST"
export const FETCH_TESTIMONIALS_SUCCESS = "FETCH_TESTIMONIALS_SUCCESS"
export const FETCH_TESTIMONIALS_FAILURE = "FETCH_TESTIMONIALS_FAILURE"